### ISSUE TITLE
issue about module importing

### ISSUE THREAD

**Issue by gangcai** [fabriziocosta/GraphEmbed#3]
```python
[user@192 bin]$ graph_embed -h
Traceback (most recent call last):
  File "/home/user/bin/miniconda2/bin/graph_embed", line 59, in <module>
    from graph_layout_embedder import Embedder
  File "/home/user/bin/miniconda2/bin/graph_layout_embedder.py", line 20, in <module>
    from sklearn.cross_validation import StratifiedKFold
ImportError: No module named cross_validation
```

**Comment by gangcai** [comment]
Should it be " from sklearn.model_selection import StratifiedKFold" for the new version of sklearn?
